import Head from 'next/head'
import Image from 'next/image'
// import { Button } from "ooush-ui"
// import Button from "../components/common/button"
import Button from "../src/components/common/button/button";
import React from "react"
import { useState } from "react"
import styles from '../styles/Home.module.css'

export default function Home() {
  const [name, setName] = useState("")
  const [nameData, setNameData] = useState(null)
  const getName = () => {
    fetch('/api/hello')
      .then(response => response.json())
      .then(data => {
        setName(data.data.firstName)
        setNameData(data.data)
      })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome <b style={{ color: "red" }}>{name}</b>
          <br />to
        </h1>
        <Button text={name.length > 0 ? "OOUSH!!!" : ""}
          textColor="red"
          textSize={48}
          backgroundColor="white"
          theme="primary"
          onClick={() => getName()}
          type="button"
          name="Ooush Button"
          borderRadius={8}
          height="100px"
          width="100%"
        />
        <div style={{margin: "16px 0"}}>{
          nameData && JSON.stringify(nameData)
        }</div>
      </main>
    </div>
  )
}
