import Head from 'next/head'
import React from "react"
import { useState } from "react"

import login from "../service/auth/authService";

import Button from "../src/components/common/button/button";

import { LOGIN_MESSAGE_TIMEOUT_MILLISECONDS } from "../utils/constants/ooush-constants"

import styles from '../styles/Home.module.css'

export default function Home() {
    const [name, setName] = useState("");
    const [nameData, setNameData] = useState(null);
    const [loginMessage, setLoginMessage] = useState("");
    const [error, setError] = useState("");

    const getName = () => {
        let data = {
            userName: "pete@ooushfitness.com",
            password: "Liverpool1",
        };
        login(data).then((response: any) => {
            displayNotification(response.loginMessage);
        }).catch((error: string)  => {
            setError(error);
            console.error("Error on login", error);
        })
    }

    const displayNotification = (message: string) => {
        setLoginMessage(message);
        setTimeout(() => {
            setLoginMessage("");
        }, LOGIN_MESSAGE_TIMEOUT_MILLISECONDS);
    }

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
                    Welcome <b style={{ color: "red" }}>{name}</b>
                    <br />to
				</h1>
				<Button text={name.length > 0 ? "OOUSH!!!" : ""}
                    textColor="red"
                    textSize={48}
                    backgroundColor="white"
                    theme="primary"
                    onClick={() => getName()}
                    type="button"
                    name="Ooush Button"
                    borderRadius={8}
                    height="100px"
                    width="100%"
				/>
				<div style={{margin: "16px 0"}}>
                    {nameData
                        && JSON.stringify(nameData)
                    }
				</div>
                <div style={{margin: "16px 0"}}>
                    {error
                        && error
                    }
                </div>
                <div style={{margin: "16px 0"}}>
                    {loginMessage
                        && loginMessage
                    }
                </div>
			</main>
		</div>
		)
	}
